### ISSUE TITLE
Authenticate behind corporate proxy

### ISSUE THREAD

**Issue by shnplr** [kndt84/passport-cognito#13]
Hi,

I have a nodejs/express app thats working great from home or deployed on EB. Great library thanks!

However at work behind our corporate proxy authentication requests seem to be timing out. AWS seem to provide a simple solution here: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html
and https://aws.amazon.com/blogs/developer/using-the-aws-sdk-for-javascript-from-behind-a-proxy/

As I'm kind of new to NodeJS I'm wondering how to pass this config when creating the CognitoStrategy object. Is it possible as I would like the option to run from my localhost?

Thanks,
Paul

**Comment by lucascebertin** [comment]
Reading the lib code, I can assume that there is no way to change httpOptions...

You should fork this repository, code the changes that you need to work behind a proxy and submit a pull request.

For now, I can help you find out where you can change... but if you need more help on it, just let me know and we can try this out together.

This line refer to the strategy object that you mentioned:
https://github.com/kndt84/passport-cognito/blob/master/lib/strategy.js#L51

Probably there is the right place for you.
