### ISSUE TITLE
newPassword2

### ISSUE THREAD

**Issue by shnplr** [kndt84/passport-cognito#14]
Hi,

On Line 142 there is a:
 console.log('newPassword2'...)

Would it be possible to comment this line out please?

Also is there a way to pass the password value into the function rather than explicit req.body.password?

The flow is
1. user enters username/password
2. server detects (err.412) and redirects to "Change Password" - the temporary password is saved on session
3. user enters newpassword
4. server gets the password from session and authenticates with password & newpassword

Currently I have to set the initial password onto the form inside hidden field (in plain text).  I guess its not a big deal since its not leaking the real password.

Cheers,
Paul

**Comment by kndt84** [comment]
Can you  pull  request? I'll merge it.
