### ISSUE TITLE
High severity vulnerability found in crypto-browserify

### ISSUE THREAD

**Issue by VarmaSANJAY** [kndt84/passport-cognito#24]
I am getting this security issue.

High severity vulnerability found in crypto-browserify
Description: Insecure Randomness
From: passport-cognito@0.1.13 > amazon-cognito-identity-js@1.31.0 > aws-sdk@2.177.0 > crypto-browserify@1.0.9

Please, consider to upgrade amazon-cognito-identity-js to 3.0.6

**Comment by kndt84** [comment]
I've updated the packages in this PR https://github.com/kndt84/passport-cognito/pull/32
