### ISSUE TITLE
Improper Authorization

### ISSUE THREAD

**Issue by AZMarkS** [kndt84/passport-cognito#38]
[NPM Audit failure](https://www.npmjs.com/advisories/1443)

All versions of passport-cognito are vulnerable to Improper Authorization. The package fails to properly scope the variables containing authorization information, such as access token, refresh token and ID token. This causes a race condition where simultaneous authenticated users may receive authorization tokens for a different user. This would allow a user to take actions on another user's behalf.

**Comment by rickhernandezio** [comment]
+1 for a fix

**Comment by LJNGDAHL** [comment]
I've made a [pull request](https://github.com/kndt84/passport-cognito/pull/41) with a fix for this issue. Is it possible to get it reviewed (and merged if everything looks okay)?

**Comment by rognstad** [comment]
It's not encouraging that the advisory has been out since May, and no fix has been released for an issue bad enough for NPM to say "don't use this package."

Thanks for putting together that PR, @LJNGDAHL! I'm using your fork for the moment.

**Comment by RLIndia** [comment]
NPM Audit failure is still showing up with the latest 0.2.2 version. Does that mean this issue is not fixed by the code merged above?
