### ISSUE TITLE
Setting user field on request

### ISSUE THREAD

**Issue by yulric** [kndt84/passport-cognito#4]
Hi there,
I was wondering if this library automatically sets the user field on the express request object for an authenticated request? Thanks.

**Comment by kndt84** [comment]
User field is set by passport module, not by this module, as following.

```
passport.serializeUser(function(user, done) {
  done(null, user.id);
});

passport.deserializeUser(function(id, done) {
  User.findById(id, function(err, user) {
    done(err, user);
  });
});
```
Reference: http://passportjs.org/docs/configure
