### ISSUE TITLE
RefreshToken?

### ISSUE THREAD

**Issue by rbudding** [kndt84/passport-cognito#7]
function(accessToken, idToken, refreshToken, user, session, cb) {
    process.nextTick(function() {
      user.expiration = session.getIdToken().getExpiration();
      ...
      cb(null, user);
    })

--> How can I use the RefreshToken if the user.expiration is true...

**Comment by kndt84** [comment]
Please refer my production code
https://gist.github.com/kndt84/39348df56d22cf902a8e387d2c55dc1c
