### ISSUE TITLE
Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by alienintheheights** [kndt84/passport-cognito#9]
The example on the README is throwing an error:

```
 $.ajax({
            type: "post",
            url: 'http://localhost:3000/auth/cognito',
            data: { username: "myname", password: "mypass" }
        })
```
```


TypeError: Cannot read property 'username' of undefined
    at CognitoStrategy.authenticate (/mypath/node_modules/passport-cognito/lib/strategy.js:76:26)
    at attempt (/mypath/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate `

```
req.body is null in authenticate()

```
CognitoStrategy.prototype.authenticate = function(req, options) {

  var user = {};
  var username = req.body.username;
  var password = req.body.password;

```

**Comment by carbonphyber** [comment]
@alienintheheights This looks like a case where you haven't [hooked up your POST body handling](https://expressjs.com/en/resources/middleware/body-parser.html#examples). This automatically done for you if you use an Express code generator/boilerplate.

If you started your Express codebase from scratch, you will need to manually hook it up for the content-types you want to support (`application/x-www-form-urlencoded`, `application/json`, etc).
